### ISSUE TITLE
DOC: Is it worthwhile to change instances of "element" to "cell" in filter names, created and required attribute arrays, feature data, etc.?

### ISSUE THREAD

**Issue by StopkaKris** [BlueQuartzSoftware/complex#927]
### Is there an existing issue for this?

- [X] I have searched the existing issues, known issues in release notes, and documentation.

### Brief Description of the Documentation Issue or Improvement

It appears that DREAM.3D refers to voxel/image data typically as "cell" but there are instances where "element" is used in filters (e.g., ```Create Element array from Feature Array```, ```Create Feature Array from Element Array```), some cell feature data (e.g., "NumElements"), and various created and required arrays in filters (e.g., "Number of Elements" in filters such as ```Find Feature Sizes```, but ```Remove Minimum Size Features``` then requires "Num Cells Array"). This is probably spillover from the use of DREAM.3D to generate input files for finite element analysis packages, but would it be worthwhile to standardize any reference to voxel/image data as only cell and not element?

Best regards,
Krzysztof Stopka

### Version

DREAM3D NX (version 7)

### What section of the documentation did you encounter the discrepancy in? [Further details may be required during triage process]

Filter Documentation

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imikejackson** [comment]
@StopkaKris Interesting observation.

This does need to be addressed. The issue is that DREAM3D-NX also has node-based geometries such as Vertex, Edge, Triangle, Quad, Hexahedron, and Tetrahedron. In those geometries the notion of a "cell" starts to become blurry when you get to the Hex and Tet geometries. A single vertex could be a "Cell", while in an Edge geometry, the "Cell" is the actual edge. Same goes for Triangle and Quad. 

Specifically, 'Create Element array from Feature Array' and  'Create Feature Array from Element Array' can be used with non-image geometries, and can actually be used with non-geometries. We can use the "Create Element array from Feature Array" to copy Ensemble data down to a Feature AttributeMatrix and then use it again, to copy from the Feature AttributeMatrix down to the actual Cell level Attribute Matrix.

The issue is that "Array Element", "Cell", "Element", "Voxel" can all be used interchangeably.

I think the endeavor is worthwhile to pursue. The supporting documentation needs to be edited with descriptions for the terminology that we are using.

**Comment by StopkaKris** [comment]
Hi @imikejackson 

Those are great points as well. Thanks for your notes on this.

Best regards,
Krzysztof Stopka

**Comment by imikejackson** [comment]
There has been some recent work that has gone into this. maybe not a wide sweeping change but we have tried to be consistent in our use of terminology. Take a look on the next RC that gets released (Probably at the end of May).
