### ISSUE TITLE
BUG: Filter search box is not consistent when looking for certain filters

### ISSUE THREAD

**Issue by StopkaKris** [BlueQuartzSoftware/complex#967]
### Is there an existing issue for this?

- [X] I have searched the existing issues, known issues in release notes, and documentation.

### Brief Description of the Issue and Expected Behavior

The search box for filters is not consistent for different phrases. For example, searching for the phrase "centroid", "find feature nei", or "phase" shows only filters with those phrases in the filter name:

![21](https://github.com/BlueQuartzSoftware/simplnx/assets/74416866/8369e81c-37c4-4832-b631-8696e71d7580)
![22](https://github.com/BlueQuartzSoftware/simplnx/assets/74416866/388a56cb-3284-4cdb-89c6-f30073fcc8b7)
![23](https://github.com/BlueQuartzSoftware/simplnx/assets/74416866/dee35b1f-d5ea-4f9b-b952-295cb7d72152)

whereas searching for "orientation", "euler", "quat", or "segment" results in filters that do not necessarily contain the search phrase:

![31](https://github.com/BlueQuartzSoftware/simplnx/assets/74416866/9115edff-b5af-4f06-bd34-caeff2cb4db5)
![32](https://github.com/BlueQuartzSoftware/simplnx/assets/74416866/5f0d4ab5-25d5-4e20-8728-ebd75268d4f0)
![33](https://github.com/BlueQuartzSoftware/simplnx/assets/74416866/e2b8c0ac-922d-4661-9289-eba324190a2f)
![34](https://github.com/BlueQuartzSoftware/simplnx/assets/74416866/76cc9779-4074-481e-98f4-acecddbc2ad5)
![35](https://github.com/BlueQuartzSoftware/simplnx/assets/74416866/eed08407-0661-4e70-9359-7518b6ec3bba)

Is there an official strategy for how this search function should work? Are there internal filter tags or keywords that control this? I bring this issue up because this may make it challenging for users to find the filters they need if some filters only show up if the search phrase is in the filter name. On the other hand, I do see the utility in presenting multiple filters that have to do with orientation to the user if the search phrase is "euler" or "quat", but at the moment, the search results for these filters are not consistent.

### Version

DREAM3D NX (version 7)

### What operating system are you seeing the problem on? [Further details may be required during triage process]

Windows 10

### What hardware architecture are you using? [Further details may be required during triage process]

x86_64

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by imikejackson** [comment]
The search box is searching all of the following:

Filter Name
Filter C++ Class Name
Tags
Name of Plugin

The thought process was try to give the user as many results that are "relevant" to what they might be looking for. Each filter has a default set of tags that are assigned at the C++ level. We open to adding more where we fell short on some of the filters.

It might be helpful in the search results to maybe have some sort of icon indicating where the search result came from so the user knows how we arrived at the result.

We used to have a small drop down menu to allow the user to narrow what/how we are search (ANY words. ALL words). It used to be ALL words but we moved it to ANY word so that the user can do more like a Google search and get back results that seem relevent.

**Comment by StopkaKris** [comment]
Hi @imikejackson Thank you for the detailed explanation.

I like the idea of adding some sort of icon so the user knows how the search phrase determined the results. Also, I admit this is a low priority change request overall.

**Comment by imikejackson** [comment]
@StopkaKris If I remember correctly, the reason we went the route we did was so that the user didn't have to know our filter names. That seems sort of ironic that you need to know the names of the filters in order to "find" the filter. So we search on the name of the filter, the human name of the filter, any tags the filter has and what plugin the filter belongs to.

So if the user is looking for something having to do with Orientation, they type that and we give them everything that has Orientation in any of those places. They can then read down through the list. The terms are a logical "AND" so they could type Orientation Quat you get 4 filters (currently) that show up.

I'm going to close this for now but we may come back around and revisit the search bar at a later date.
